-- ============================================================
-- ⭐ BTC RECEIPTS — ไฟล์ SQL รวมทุกอย่าง (ONE STOP — รันซ้ำได้ตลอด)
-- ============================================================
-- วิธีใช้: Supabase Dashboard > SQL Editor > New query > วางทั้งหมดนี้ > Run
-- ข้อดี: รันซ้ำกี่รอบก็ได้ (idempotent — ไม่พังไม่ซ้ำซ้อน) เหมาะสำหรับ
--        "อัปเดต/ปรับปรุง" ในอนาคต — แก้ไฟล์นี้ไฟล์เดียว แล้วรันซ้ำ = schema สดเสมอ
--
-- มีอะไรบ้าง (เรียงลำดับปลอดภัย):
--   [1] receipts: เปิด anon อ่านได้ + Realtime
--   [2] receipts: เพิ่มคอลัมน์ใบชั่ง (น้ำหนัก/ทะเบียนรถ)
--   [3] receipts: เพิ่มคอลัมน์สั่งซื้อ/งาน (ชื่อบริษัท/งาน/ผู้เบิก/ผู้สั่งจ่าย)
--   [4] ตาราง receipt_links: จับคู่บิลรับของ ↔ ใบสั่งซื้อ (RLS anon อ่าน)
--   [5] ตาราง receipt_learning: เรียนรู้ AI (RLS ปิด anon — ใช้ GAS อย่างเดียว)
--   [6] ตาราง doc_types: ประเภทเอกสารองค์กร (RLS anon อ่านเฉพาะ is_active)
--   [9] ตาราง ai_templates: ตัวอย่างบิลสำหรับ AI (แม่แบบ + เก็บ layout) Phase 1
--   [10] ตาราง ai_prompts: ชุด prompt AI ต่อประเภท "AI เขียนเอง" Phase 2
--        + migration: ai_templates.doc_type → predicted_doc_type แล้ว doc_type=NULL
--   [11] ตาราง ai_feedback_logs: Human-in-the-Loop (AI Active Learning)
--   [12] ตาราง vendor_billing: ใบวางบิล + รายการผูกบิล
--   [13] receipts: เลขที่รายการของระบบ (System Record No.) — รันต่อเนื่องห้ามซ้ำ + สร้างย้อนหลังเอกสารเก่า
--   [7] ตรวจผลรวมทุกส่วนท้ายไฟล์ (รวมส่วน AI)
--   [8] SELF-HEAL: ให้สิทธิ์ซ้ำทุกครั้งที่รัน (ครอบคลุม doc_types / receipt_learning / views ธุรกิจ ด้วย) + รายงาน 1 แถว
--
-- หมายเหตุ: ถ้าอยากรู้ว่าส่วนไหนทำอะไร อ่าน block ตามหมายเลขได้เลย
--           ส่วนที่รันแล้วจะ "ข้าม" อย่างปลอดภัย (IF NOT EXISTS / IF EXISTS)
--           รันครั้งไหนมี error ตัวแดง = เอาเฉพาะข้อความแดงนั้นมาแจ้ง (ที่เหลือน่าจะผ่านหมด)
-- ============================================================

-- อนุญาตใช้ schema public ให้ทุกบทบาทที่ใช้ (กันสิทธิ์ schema ไม่ให้อ่านไม่ได้)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- ════════════════════════════════════════════════════════════
-- [1] receipts: เปิด RLS + anon อ่านได้ + เปิด Realtime
-- ════════════════════════════════════════════════════════════
ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.receipts TO anon;

DROP POLICY IF EXISTS "anon_read_receipts" ON public.receipts;
CREATE POLICY "anon_read_receipts"
  ON public.receipts
  FOR SELECT
  TO anon
  USING (true);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename  = 'receipts'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.receipts;
  END IF;
END $$;

-- ════════════════════════════════════════════════════════════
-- [2] receipts: คอลัมน์ใบชั่ง (น้ำหนัก + ทะเบียนรถ)
-- ════════════════════════════════════════════════════════════
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS scale_weight_in numeric;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS scale_weight_out numeric;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS scale_weight_net numeric;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS vehicle_registration text;

GRANT SELECT(scale_weight_in, scale_weight_out, scale_weight_net, vehicle_registration)
  ON public.receipts TO anon;

GRANT SELECT, INSERT, UPDATE(scale_weight_in, scale_weight_out, scale_weight_net, vehicle_registration)
  ON public.receipts TO service_role;

-- ════════════════════════════════════════════════════════════
-- [3] receipts: คอลัมน์สั่งซื้อ/งาน (AI อ่านจากใบสั่งซื้อ)
--       company_name (บริษัทผู้สั่งซื้อ) / job_name (งาน) /
--       requester (ผู้เบิก) / pay_approver (ผู้สั่งจ่าย)
-- ════════════════════════════════════════════════════════════
ALTER TABLE public.receipts
  ADD COLUMN IF NOT EXISTS company_name text,
  ADD COLUMN IF NOT EXISTS job_name text,
  ADD COLUMN IF NOT EXISTS requester text,
  ADD COLUMN IF NOT EXISTS pay_approver text;

GRANT SELECT(company_name, job_name, requester, pay_approver)
  ON public.receipts TO anon;

GRANT SELECT, INSERT, UPDATE(company_name, job_name, requester, pay_approver)
  ON public.receipts TO service_role;

-- ════════════════════════════════════════════════════════════
-- [4] ตาราง receipt_links — จับคู่บิลรับของ ↔ ใบสั่งซื้อ
--     สถานะ: pending (รอตรวจสอบ) → confirmed (จับคู่แล้ว)
--     anon อ่านได้ (หน้าเว็บโชว์คู่/คำแนะนำ) เขียนผ่าน GAS (service_role) เท่านั้น
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.receipt_links (
  id bigint generated by default as identity primary key,
  po_doc_key text not null,
  po_label text default '',
  po_store_name text default '',
  link_doc_key text not null,
  link_label text default '',
  link_store_name text default '',
  link_type text default '',
  link_scale_net numeric,
  link_vehicle text default '',
  status text not null default 'pending' check (status in ('pending', 'confirmed')),
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  UNIQUE (po_doc_key, link_doc_key)
);

ALTER TABLE public.receipt_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read_receipt_links" ON public.receipt_links;
CREATE POLICY "anon_read_receipt_links"
  ON public.receipt_links
  FOR SELECT
  TO anon, authenticated
  USING (true);

REVOKE ALL ON public.receipt_links FROM anon, authenticated;
GRANT SELECT ON public.receipt_links TO anon, authenticated;   -- สำคัญ: กันกรณี default privilege ไม่ให้สิทธิ์อ่าน
GRANT ALL ON public.receipt_links TO service_role;

CREATE INDEX IF NOT EXISTS idx_receipt_links_po ON public.receipt_links (po_doc_key);
CREATE INDEX IF NOT EXISTS idx_receipt_links_link ON public.receipt_links (link_doc_key);

-- ════════════════════════════════════════════════════════════
-- [5] ตาราง receipt_learning — เรียนรู้ AI (AI อ่าน → มนุษย์แก้)
--     ปิด anon/authenticated สนิท — ใช้ GAS (service_role) เท่านั้น
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.receipt_learning (
  id bigint generated by default as identity primary key,
  field_name text not null,
  ai_value text not null default '',
  human_value text not null,
  doc_key text default '',
  learn_count int not null default 1,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS receipt_learning_field_ai_idx
  ON public.receipt_learning (field_name, ai_value);

ALTER TABLE public.receipt_learning ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.receipt_learning FROM anon, authenticated;
GRANT ALL ON public.receipt_learning TO service_role;

-- ════════════════════════════════════════════════════════════
-- [6] ตาราง doc_types — ประเภทเอกสารเฉพาะองค์กร
--     anon อ่านได้เฉพาะ is_active = true (เติม dropdown หน้าเว็บ)
--     เขียน/ลบ ผ่าน GAS (service_role) เท่านั้น
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.doc_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  aliases text[] default '{}',
  treat_as_scale boolean default false,
  is_active boolean default true,
  sort_order int default 100,
  created_at timestamptz not null default now()
);

-- ทะเบียนประเภทเอกสารมาตรฐานบัญชี/ภาษี: เก็บ metadata สำหรับ UI/AI โดยคง receipts.doc_type เป็นชื่อไทยเดิม
ALTER TABLE public.doc_types ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.doc_types ADD COLUMN IF NOT EXISTS accounting_group text;
ALTER TABLE public.doc_types ADD COLUMN IF NOT EXISTS vat_treatment text;
ALTER TABLE public.doc_types ADD COLUMN IF NOT EXISTS legal_reference text;
ALTER TABLE public.doc_types ADD COLUMN IF NOT EXISTS is_standard boolean NOT NULL DEFAULT false;
UPDATE public.doc_types SET is_standard = false WHERE is_standard IS NULL;

INSERT INTO public.doc_types
  (name, code, accounting_group, vat_treatment, legal_reference, aliases, treat_as_scale, is_standard, is_active, sort_order)
VALUES
  ('ใบกำกับภาษี', 'TAX', 'Tax & Receipts', 'พิจารณาเครดิตภาษีซื้อได้เมื่อเอกสารถูกต้องครบถ้วน', 'ประมวลรัษฎากร ม.86/4', ARRAY['Tax Invoice'], false, true, true, 10),
  ('ใบเสร็จรับเงิน', 'REC', 'Tax & Receipts', 'หลักฐานรับชำระเงิน ไม่ใช่หลักฐานเครดิต VAT โดยลำพัง', 'ประมวลรัษฎากร ม.105', ARRAY['Receipt'], false, true, true, 20),
  ('ใบเสร็จรับเงิน/ใบกำกับภาษี', 'REC/TAX', 'Tax & Receipts', 'พิจารณาเครดิตภาษีซื้อได้เมื่อเอกสารถูกต้องครบถ้วน', 'ประมวลรัษฎากร ม.86/4, ม.105', ARRAY['Receipt / Tax Invoice'], false, true, true, 30),
  ('ใบลดหนี้', 'CN', 'Tax & Receipts', 'ใช้ปรับลดภาษีซื้อและยอดซื้อตามเอกสารที่ถูกต้อง', 'ประมวลรัษฎากร ม.86/10', ARRAY['Credit Note'], false, true, true, 40),
  ('ใบเพิ่มหนี้', 'DN', 'Tax & Receipts', 'ใช้ปรับเพิ่มภาษีซื้อและยอดซื้อตามเอกสารที่ถูกต้อง', 'ประมวลรัษฎากร ม.86/9', ARRAY['Debit Note'], false, true, true, 50),
  ('หนังสือรับรองการหักภาษี ณ ที่จ่าย (50 ทวิ)', 'WHT', 'Tax & Receipts', 'หลักฐานภาษีหัก ณ ที่จ่าย ไม่ใช่เครดิตภาษีซื้อ VAT', 'ประมวลรัษฎากร ม.50 ทวิ', ARRAY['50 ทวิ','Withholding Tax Certificate'], false, true, true, 60),
  ('ใบส่งของ/ใบกำกับภาษี', 'DO/TAX', 'Delivery & Site Operations', 'พิจารณาเครดิตภาษีซื้อได้เมื่อส่วนใบกำกับภาษีถูกต้องครบถ้วน', 'ประมวลรัษฎากร ม.86/4', ARRAY['Delivery Order / Tax Invoice'], false, true, true, 70),
  ('ใบส่งของ', 'DO', 'Delivery & Site Operations', 'หลักฐานส่งมอบ ไม่ใช่เครดิตภาษีซื้อ VAT โดยลำพัง', NULL, ARRAY['Delivery Order','Delivery Note'], false, true, true, 80),
  ('ใบส่งของ/ใบแจ้งหนี้', 'DO/INV', 'Delivery & Site Operations', 'เอกสารฉบับเดียวเป็นทั้งหลักฐานส่งมอบและเรียกเก็บเงิน ต้องติดตามหลักฐานภาษี/รับชำระประกอบ', NULL, ARRAY['Delivery Order / Invoice','ใบส่งของ/ใบวางบิล'], false, true, true, 85),
  ('ใบชั่ง', 'WT', 'Delivery & Site Operations', 'หลักฐานน้ำหนักหน้างาน ไม่ใช่เครดิตภาษีซื้อ VAT', NULL, ARRAY['Weight Ticket','Weighbridge'], true, true, true, 90),
  ('ใบตรวจรับพัสดุ/งานจ้าง', 'WR', 'Delivery & Site Operations', 'หลักฐานตรวจรับภายใน ไม่ใช่เครดิตภาษีซื้อ VAT โดยลำพัง', NULL, ARRAY['Work Acceptance Report','ใบรับมอบงาน'], false, true, true, 100),
  ('ใบสั่งซื้อ', 'PO', 'Purchasing & Commercial', 'เอกสารสั่งซื้อ ไม่ใช่เครดิตภาษีซื้อ VAT', NULL, ARRAY['Purchase Order','P.O.'], false, true, true, 110),
  ('ใบขอซื้อ/ใบขอเบิก', 'PR', 'Purchasing & Commercial', 'เอกสารคำขอภายใน ไม่ใช่เครดิตภาษีซื้อ VAT', NULL, ARRAY['Purchase Requisition'], false, true, true, 120),
  ('ใบวางบิล/ใบแจ้งหนี้', 'INV/BILL', 'Purchasing & Commercial', 'เอกสารเรียกเก็บเงิน ต้องติดตามหลักฐานภาษี/รับชำระประกอบ', NULL, ARRAY['Billing','Invoice'], false, true, true, 130),
  ('ใบเสนอราคา', 'QT', 'Purchasing & Commercial', 'เอกสารเสนอราคา ไม่ใช่เครดิตภาษีซื้อ VAT', NULL, ARRAY['Quotation','Quote'], false, true, true, 140),
  ('ใบสำคัญจ่าย', 'PV', 'Internal Accounting Vouchers', 'เอกสารภายใน ต้องมีหลักฐานภาษีภายนอกประกอบหากจะพิจารณา VAT', NULL, ARRAY['Payment Voucher'], false, true, true, 150),
  ('ใบสำคัญรับ', 'RV', 'Internal Accounting Vouchers', 'เอกสารภายใน ไม่ใช่เครดิตภาษีซื้อ VAT โดยลำพัง', NULL, ARRAY['Receive Voucher','Receipt Voucher'], false, true, true, 160),
  ('ใบเบิกเงินสดย่อย', 'PC', 'Internal Accounting Vouchers', 'เอกสารภายใน ต้องมีหลักฐานภาษีภายนอกประกอบหากจะพิจารณา VAT', NULL, ARRAY['Petty Cash Voucher'], false, true, true, 170)
ON CONFLICT (name) DO UPDATE SET
  code = EXCLUDED.code,
  accounting_group = EXCLUDED.accounting_group,
  vat_treatment = EXCLUDED.vat_treatment,
  legal_reference = EXCLUDED.legal_reference,
  aliases = EXCLUDED.aliases,
  treat_as_scale = EXCLUDED.treat_as_scale,
  is_standard = true,
  is_active = true,
  sort_order = EXCLUDED.sort_order;

ALTER TABLE public.doc_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read_active_doc_types" ON public.doc_types;
CREATE POLICY "anon_read_active_doc_types"
  ON public.doc_types
  FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

REVOKE INSERT, UPDATE, DELETE ON public.doc_types FROM anon, authenticated;
GRANT ALL ON public.doc_types TO service_role;

-- ════════════════════════════════════════════════════════════
-- [9] ตาราง ai_templates — ตัวอย่างบิลสำหรับ AI (Phase 1: แม่แบบ + เก็บ layout)
--     เก็บภาพบิลจริง + ground truth (คำตอบที่ถูกต้อง) เพื่อให้ AI เรียนรู้รูปแบบ
--     doc_type ความหมายหลัง [10]: "หมวดที่ User จัดให้" (NULL = ยังไม่จัด)
--     anon อ่านได้เฉพาะ active / เขียนทั้งหมดผ่าน GAS (service_role)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.ai_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_type text,                       -- หมวดที่ User จัดให้ (ว่าง = ยังไม่จัด)
  drive_file_id text NOT NULL,         -- Google Drive file ID
  drive_folder_path text NOT NULL,     -- path ใน Drive (AI_Templates/pending/ | AI_Templates/active/)
  ground_truth jsonb NOT NULL DEFAULT '{}',  -- JSON คำตอบที่ถูกต้อง (user verified)
  few_shot_prompt text,                -- few-shot block (legacy Phase 1)
  layout_signature text,               -- hash คร่าว ๆ (aHash:32x32:<16hex>) สำหรับ matching
  cluster_id text,                     -- รหัสกลุ่มจาก clustering (phase 3+)
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','archived')),
  usage_count integer NOT NULL DEFAULT 0,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_templates_doc_type ON public.ai_templates (doc_type);
CREATE INDEX IF NOT EXISTS idx_ai_templates_status ON public.ai_templates (status);
CREATE INDEX IF NOT EXISTS idx_ai_templates_cluster ON public.ai_templates (cluster_id);
CREATE INDEX IF NOT EXISTS idx_ai_templates_layout_sig ON public.ai_templates (layout_signature);

-- คอลัมน์ Phase 2 (เพิ่มไว้ที่นี่ก่อนสร้าง view ข้างล่าง): predicted = หมวดที่ AI ทาย, source = แหล่งเก็บ
ALTER TABLE public.ai_templates ADD COLUMN IF NOT EXISTS predicted_doc_type text;
ALTER TABLE public.ai_templates ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'line_auto';
CREATE INDEX IF NOT EXISTS idx_ai_templates_predicted ON public.ai_templates (predicted_doc_type);

REVOKE ALL ON public.ai_templates FROM anon, authenticated;
GRANT SELECT ON public.ai_templates TO anon;
GRANT ALL ON public.ai_templates TO service_role;
ALTER TABLE public.ai_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon read active templates" ON public.ai_templates;
CREATE POLICY "anon read active templates" ON public.ai_templates
  FOR SELECT TO anon USING (status = 'active');

DROP POLICY IF EXISTS "service role full access" ON public.ai_templates;
CREATE POLICY "service role full access" ON public.ai_templates
  FOR ALL TO service_role USING (true);

-- ฟังก์ชันกลาง: อัปเดต updated_at อัตโนมัติ (ใช้กับทุกตารางที่ trigger เรียก)
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trigger_ai_templates_updated_at ON public.ai_templates;
CREATE TRIGGER trigger_ai_templates_updated_at
  BEFORE UPDATE ON public.ai_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- View สำหรับ UI (thumbnail + view URL)
CREATE OR REPLACE VIEW public.v_ai_templates_ui AS
SELECT
  id, doc_type, predicted_doc_type, source, drive_file_id, drive_folder_path,
  ground_truth, few_shot_prompt, layout_signature, cluster_id, status, usage_count,
  created_by, created_at, updated_at,
  'https://drive.google.com/thumbnail?id=' || drive_file_id || '&sz=w300' AS thumbnail_url,
  'https://drive.google.com/file/d/' || drive_file_id || '/view' AS drive_view_url
FROM public.ai_templates
ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'active' THEN 1 ELSE 2 END, created_at DESC;

-- ให้สิทธิ์อ่าน view (กัน HTTP 403 — GAS ใช้ service_role, หน้าเว็บอ่านผ่าน anon)
REVOKE ALL ON public.v_ai_templates_ui FROM anon, authenticated;
GRANT SELECT ON public.v_ai_templates_ui TO anon, authenticated;
GRANT SELECT ON public.v_ai_templates_ui TO service_role;

-- RPC: หาแม่แบบที่ match (rule-based: doc_type คุมหลัก + hamming distance เรียง + usage)
CREATE OR REPLACE FUNCTION public.find_matching_templates(
  p_doc_type text,
  p_signature text,
  p_threshold integer DEFAULT 10,
  p_limit integer DEFAULT 3
)
RETURNS SETOF public.ai_templates
LANGUAGE plpgsql STABLE AS $$
DECLARE sigEmpty boolean;
BEGIN
  sigEmpty := (p_signature IS NULL OR p_signature = '');
  RETURN QUERY
  SELECT t.*
  FROM public.ai_templates t
  WHERE t.status = 'active' AND t.doc_type = p_doc_type
  ORDER BY
    (CASE WHEN sigEmpty OR t.layout_signature IS NULL OR t.layout_signature = ''
          THEN 0 ELSE hamming_distance(t.layout_signature, p_signature) END),
    t.usage_count DESC
  LIMIT p_limit;
END $$;

-- RPC: Hamming distance สำหรับ layout hash (รับ "aHash:32x32:<16hex>" หรือ "<16hex>" — เทียบ 16 หลักท้าย)
CREATE OR REPLACE FUNCTION public.hamming_distance(hex1 text, hex2 text)
RETURNS integer
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
  h1 text; h2 text; b1 bit(64); b2 bit(64); diff bit(64);
  cnt integer := 0; i integer;
BEGIN
  h1 := trim(right(coalesce(hex1, ''), 16));
  h2 := trim(right(coalesce(hex2, ''), 16));
  IF h1 = '' OR h2 = '' OR h1 !~ '^[0-9a-fA-F]{16}$' OR h2 !~ '^[0-9a-fA-F]{16}$' THEN
    RETURN 999;
  END IF;
  b1 := decode(h1, 'hex')::bit(64);
  b2 := decode(h2, 'hex')::bit(64);
  diff := b1 # b2;
  FOR i IN 0..63 LOOP
    IF diff[i] = 1 THEN cnt := cnt + 1; END IF;
  END LOOP;
  RETURN cnt;
END $$;

-- RPC: นับการใช้งานแม่แบบ (service_role เท่านั้น)
CREATE OR REPLACE FUNCTION public.increment_template_usage(template_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  UPDATE public.ai_templates SET usage_count = usage_count + 1 WHERE id = template_id;
END $$;

REVOKE ALL ON FUNCTION public.increment_template_usage(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.increment_template_usage(uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.increment_template_usage(uuid) TO service_role;

-- ════════════════════════════════════════════════════════════
-- [10] ตาราง ai_prompts — ชุด prompt AI ต่อประเภท "AI เขียนเอง" (Phase 2)
--      User ลากตัวอย่างบิลไปวางในหมวด → AI ดูตัวอย่าง+ความรู้บัญชี แล้วเขียนชุดคำสั่งอ่านเอง
--      ตอนอ่านบิลใหม่ ฉีด "ชุด prompt ของหมวด" + ตัวอย่างเข้าช่วย Gemini
--      migration: ai_templates.doc_type ถูก "ย้ายขา" มาเป็น predicted_doc_type (รันซ้ำไม่ย้ายซ้ำ)
-- ════════════════════════════════════════════════════════════
-- migration ทีละครั้งเท่านั้น: ถ้ายังไม่เคยย้าย (predicted ว่างและ doc_type มีค่า) → ย้ายไป predicted แล้วเคลียร์ doc_type
UPDATE public.ai_templates
SET predicted_doc_type = COALESCE(predicted_doc_type, NULLIF(doc_type, ''))
WHERE NULLIF(doc_type, '') IS NOT NULL AND COALESCE(predicted_doc_type, '') = '';

UPDATE public.ai_templates
SET doc_type = NULL
WHERE NULLIF(doc_type, '') IS NOT NULL AND COALESCE(predicted_doc_type, '') <> '';

CREATE TABLE IF NOT EXISTS public.ai_prompts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_type text UNIQUE NOT NULL,
  title text NOT NULL DEFAULT '',
  kind text NOT NULL DEFAULT 'custom' CHECK (kind IN ('standard','custom')),
  status text NOT NULL DEFAULT 'sample_needed'
      CHECK (status IN ('sample_needed','ready','generating')),
  prompt_text text NOT NULL DEFAULT '',
  base_knowledge text NOT NULL DEFAULT '',
  field_config jsonb NOT NULL DEFAULT '{}',
  sample_count integer NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 0,
  created_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.ai_prompts ADD COLUMN IF NOT EXISTS field_config jsonb NOT NULL DEFAULT '{}';
ALTER TABLE public.ai_prompts ADD COLUMN IF NOT EXISTS prompt_seed_version integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_ai_prompts_doc_type ON public.ai_prompts (doc_type);
CREATE INDEX IF NOT EXISTS idx_ai_prompts_status ON public.ai_prompts (status);

REVOKE ALL ON public.ai_prompts FROM anon, authenticated;
GRANT SELECT ON public.ai_prompts TO anon;
GRANT ALL ON public.ai_prompts TO service_role;
ALTER TABLE public.ai_prompts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon read ai_prompts" ON public.ai_prompts;
CREATE POLICY "anon read ai_prompts" ON public.ai_prompts
  FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "service role full access ai_prompts" ON public.ai_prompts;
CREATE POLICY "service role full access ai_prompts" ON public.ai_prompts
  FOR ALL TO service_role USING (true);

DROP TRIGGER IF EXISTS trigger_ai_prompts_updated_at ON public.ai_prompts;
CREATE TRIGGER trigger_ai_prompts_updated_at
  BEFORE UPDATE ON public.ai_prompts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- RPC: อัปเดต sample_count ให้ชุด prompt (service_role เท่านั้น)
CREATE OR REPLACE FUNCTION public.refresh_prompt_sample_count(p_doc_type text)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM public.ai_templates
  WHERE doc_type = p_doc_type AND status <> 'archived';
  UPDATE public.ai_prompts SET sample_count = n WHERE doc_type = p_doc_type;
  RETURN n;
END $$;

REVOKE ALL ON FUNCTION public.refresh_prompt_sample_count(text) FROM anon;
REVOKE ALL ON FUNCTION public.refresh_prompt_sample_count(text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_prompt_sample_count(text) TO service_role;

-- View สำหรับหน้า UI (ชุด prompt + จำนวนตัวอย่าง)
CREATE OR REPLACE VIEW public.v_ai_prompts_ui AS
SELECT
  p.id, p.doc_type, p.title, p.kind, p.status, p.prompt_text, p.base_knowledge,
  p.sample_count, p.version, p.created_by, p.created_at, p.updated_at,
  p.field_config
FROM public.ai_prompts p
ORDER BY p.kind DESC, p.doc_type ASC;

-- ให้สิทธิ์อ่าน view (กัน HTTP 403 — GAS ใช้ service_role, หน้าเว็บอ่านผ่าน anon)
REVOKE ALL ON public.v_ai_prompts_ui FROM anon, authenticated;
GRANT SELECT ON public.v_ai_prompts_ui TO anon, authenticated;
GRANT SELECT ON public.v_ai_prompts_ui TO service_role;

-- ════════════════════════════════════════════════════════════
-- [11] ai_feedback_logs — Human-in-the-Loop (original_ai_data vs user_corrected_data)
--       AI Active Learning: บันทึกทุกครั้งที่ User แก้ข้อมูลบิล / ยืนยัน-แก้การจับคู่
--       แล้วเอากลับมาฉีดเป็น Few-Shot ต่อร้าน ตอน AI อ่านบิลใหม่ (getStoreFeedbackContext)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.ai_feedback_logs (
  id bigint generated by default as identity primary key,
  doc_key text not null default '',            -- ตัวตนบิล (Doc Key)
  doc_type text not null default '',           -- ประเภทเอกสาร (สำหรับระบบเอกสารสำหรับ AI)
  store_name text not null default '',         -- ชื่อร้าน/ซัพพลายเออร์ (เทียบ few-shot ต่อร้าน)
  action_type text not null default 'field_correct',
  field_name text not null default '',         -- ชื่อฟิลด์ที่แก้ (mapping: field_name)
  original_ai_value text not null default '',  -- ค่าที่ AI อ่านเดิม
  user_corrected_value text not null default '', -- ค่าที่มนุษย์แก้/ยืนยัน
  created_by text not null default 'user',     -- user / system
  created_at timestamptz not null default now(),
  CONSTRAINT ck_ai_feedback_action CHECK (action_type IN ('field_correct', 'match_confirm', 'match_remove', 'match_manual'))
);

CREATE INDEX IF NOT EXISTS idx_ai_feedback_store_time ON public.ai_feedback_logs (store_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_dockey ON public.ai_feedback_logs (doc_key);

ALTER TABLE public.ai_feedback_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read_ai_feedback" ON public.ai_feedback_logs;
CREATE POLICY "anon_read_ai_feedback"
  ON public.ai_feedback_logs
  FOR SELECT
  TO anon, authenticated
  USING (true);

REVOKE ALL ON public.ai_feedback_logs FROM anon, authenticated;
GRANT SELECT ON public.ai_feedback_logs TO anon, authenticated;  -- UI/Realtime อ่าน history ได้
GRANT ALL ON public.ai_feedback_logs TO service_role;            -- GAS เขียนบันทึก feedback

-- Realtime สำหรับ ai_feedback_logs (UI ฟีดแบ็กสดได้)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename  = 'ai_feedback_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_feedback_logs;
  END IF;
END $$;

-- ════════════════════════════════════════════════════════════
-- [11B] receipt_links: เพิ่ม Provenance ของการจับคู่ (Background Matcher + Manual)
--       match_type = AUTO_EXACT | AUTO_SUGGESTED | MANUAL
--       confidence_score = 0-1 / remark_text = ข้อความในช่องหมายเหตุที่ใช้จับคู่
-- ════════════════════════════════════════════════════════════
ALTER TABLE public.receipt_links ADD COLUMN IF NOT EXISTS match_type text DEFAULT 'MANUAL'
  CHECK (match_type IN ('AUTO_EXACT', 'AUTO_SUGGESTED', 'MANUAL'));
ALTER TABLE public.receipt_links ADD COLUMN IF NOT EXISTS confidence_score numeric DEFAULT 0;
ALTER TABLE public.receipt_links ADD COLUMN IF NOT EXISTS remark_text text DEFAULT '';

-- ════════════════════════════════════════════════════════════
-- [12] VENDOR BILLING + GOOGLE DRIVE REFERENCES
--      ใช้ receipts/receipt_links เดิมเป็น transaction หลัก ไม่สร้าง bills/PO ซ้ำ
--      vendor_billing_notes = ใบวางบิลร้านค้า, vendor_billing_items = บิลที่แนบในใบวางบิล
-- ════════════════════════════════════════════════════════════
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS google_drive_file_id text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS vendor_tax_id text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS project_location text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS vat_amount numeric;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS remark_text text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS extracted_po_code text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS match_type text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS confidence_score numeric;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS match_reason text;
CREATE INDEX IF NOT EXISTS idx_receipts_drive_file_id ON public.receipts (google_drive_file_id);

ALTER TABLE public.receipt_links ADD COLUMN IF NOT EXISTS google_drive_file_id text;

CREATE TABLE IF NOT EXISTS public.vendor_billing_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_name text NOT NULL,
  billing_no text NOT NULL DEFAULT '',
  billing_date date,
  claimed_amount numeric NOT NULL DEFAULT 0,
  matched_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','matched','validated','paid','rejected')),
  validation_ok boolean NOT NULL DEFAULT false,
  validation_message text NOT NULL DEFAULT '',
  drive_file_id text,
  webview_link text,
  created_by text NOT NULL DEFAULT 'user',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  validated_at timestamptz,
  paid_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.vendor_billing_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_note_id uuid NOT NULL REFERENCES public.vendor_billing_notes(id) ON DELETE CASCADE,
  receipt_doc_key text NOT NULL,
  matched_amount numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (billing_note_id, receipt_doc_key)
);

CREATE INDEX IF NOT EXISTS idx_vendor_billing_vendor_status
  ON public.vendor_billing_notes (vendor_name, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vendor_billing_items_note
  ON public.vendor_billing_items (billing_note_id);
CREATE INDEX IF NOT EXISTS idx_vendor_billing_items_receipt
  ON public.vendor_billing_items (receipt_doc_key);

ALTER TABLE public.vendor_billing_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_billing_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_vendor_billing_notes" ON public.vendor_billing_notes;
CREATE POLICY "anon_read_vendor_billing_notes" ON public.vendor_billing_notes
  FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_read_vendor_billing_items" ON public.vendor_billing_items;
CREATE POLICY "anon_read_vendor_billing_items" ON public.vendor_billing_items
  FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL ON public.vendor_billing_notes FROM anon, authenticated;
GRANT SELECT ON public.vendor_billing_notes TO anon, authenticated;
GRANT ALL ON public.vendor_billing_notes TO service_role;
REVOKE ALL ON public.vendor_billing_items FROM anon, authenticated;
GRANT SELECT ON public.vendor_billing_items TO anon, authenticated;
GRANT ALL ON public.vendor_billing_items TO service_role;

DROP TRIGGER IF EXISTS trigger_vendor_billing_notes_updated_at ON public.vendor_billing_notes;
CREATE TRIGGER trigger_vendor_billing_notes_updated_at
  BEFORE UPDATE ON public.vendor_billing_notes
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'vendor_billing_notes') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vendor_billing_notes;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'vendor_billing_items') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vendor_billing_items;
  END IF;
END $$;

-- Business-facing names; underlying data remains in the existing canonical tables.
CREATE OR REPLACE VIEW public.bills AS SELECT * FROM public.receipts;
CREATE OR REPLACE VIEW public.purchase_orders AS
  SELECT * FROM public.receipts WHERE doc_type = 'ใบสั่งซื้อ';
CREATE OR REPLACE VIEW public.po_invoice_matches AS SELECT * FROM public.receipt_links;
CREATE OR REPLACE VIEW public.ai_document_templates AS
  SELECT id, doc_type, title, kind, status, prompt_text, base_knowledge,
    sample_count, version, created_by, created_at, updated_at, field_config
  FROM public.ai_prompts;

GRANT SELECT ON public.bills, public.purchase_orders, public.po_invoice_matches, public.ai_document_templates
  TO anon, authenticated, service_role;

-- ════════════════════════════════════════════════════════════
-- [13] receipts: เลขที่รายการของระบบ (System Record No.)
--      เลขรันต่อเนื่อง (Sequential) ห้ามซ้ำเด็ดขาด — ใช้อ้างอิงเวลาแก้ไข/อัปเดตข้อมูล
--      สร้างย้อนหลังอัตโนมัติ: ครั้งแรกที่รันไฟล์นี้ เติมเลขให้เอกสารเก่าทุกใบ
--      (เรียงตามเวลาบันทึก ก่อน→หลัง — รันซ้ำจะไม่ขยับ/ไม่เปลี่ยนเลขเดิม)
-- ════════════════════════════════════════════════════════════
CREATE SEQUENCE IF NOT EXISTS receipts_srn_seq START 1;

ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS system_record_no bigint;

-- แถวที่เพิ่มใหม่โดยไม่ระบุเลข = ฐานข้อมูลเติมเลขถัดไปให้เอง (กันซ้ำระดับฐานข้อมูล — atomic)
ALTER TABLE public.receipts ALTER COLUMN system_record_no SET DEFAULT nextval('receipts_srn_seq');

-- ห้ามซ้ำเด็ดขาด: เลขซ้ำจะ INSERT ไม่ผ่านทันที (unique ระดับ DB)
CREATE UNIQUE INDEX IF NOT EXISTS uq_receipts_system_record_no
  ON public.receipts (system_record_no) WHERE system_record_no IS NOT NULL;

-- สร้างย้อนหลัง: เติมเลขให้แถวเก่าที่ยังว่าง เรียงตามเวลาบันทึกก่อน→หลัง (รันซ้ำ = แถวที่มีเลขแล้วไม่ถูกแตะ)
UPDATE public.receipts r
SET system_record_no = s.n
FROM (
  SELECT ctid, nextval('receipts_srn_seq') AS n
  FROM public.receipts
  WHERE system_record_no IS NULL
  ORDER BY submitted_at ASC, ctid
) s
WHERE r.ctid = s.ctid;

GRANT SELECT(system_record_no) ON public.receipts TO anon;

-- ตรวจเลขที่รายการ (ควรได้ has_column=1 / rows_without_no=0 และ min/max = ช่วงเลขที่ใช้ไป)
SELECT
  (SELECT count(*) FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'receipts' AND column_name = 'system_record_no') AS has_column,
  (SELECT count(*) FROM public.receipts WHERE system_record_no IS NULL) AS rows_without_no,
  (SELECT min(system_record_no) FROM public.receipts) AS min_no,
  (SELECT max(system_record_no) FROM public.receipts) AS max_no;

-- 7.1E คอลัมน์ AI feedback + match provenance (ต้องได้ 5 แถวคอลัมน์ใหม่)
SELECT table_name, column_name
FROM information_schema.columns
WHERE table_schema = 'public'
  AND (
    (table_name = 'receipt_links' AND column_name IN ('match_type', 'confidence_score', 'remark_text'))
    OR (table_name = 'ai_feedback_logs' AND column_name IN ('original_ai_value', 'user_corrected_value'))
  )
ORDER BY table_name, column_name;

-- ════════════════════════════════════════════════════════════
-- [7] ตรวจผลรวม — ดูว่าได้ครบทุกอย่างจริง
-- ════════════════════════════════════════════════════════════
-- 7.1 ตารางทั้ง 3 (ต้องได้ 3 แถว: receipt_links / receipt_learning / doc_types)
SELECT tablename FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('receipt_links', 'receipt_learning', 'doc_types')
ORDER BY tablename;

-- 7.1B ตาราง AI (ต้องได้ 3 แถว: ai_templates / ai_prompts / ai_feedback_logs)
SELECT tablename FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('ai_templates', 'ai_prompts', 'ai_feedback_logs')
ORDER BY tablename;

-- 7.1C ฟังก์ชัน RPC ของ AI (ต้องได้ 3 แถว: hamming_distance / increment_template_usage / refresh_prompt_sample_count)
SELECT p.proname FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.proname IN ('hamming_distance', 'increment_template_usage', 'refresh_prompt_sample_count')
ORDER BY p.proname;

-- 7.1D คอลัมน์ที่ AI ใช้ (ต้องได้ 2 แถว: predicted_doc_type / source)
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'ai_templates'
  AND column_name IN ('predicted_doc_type', 'source')
ORDER BY column_name;

-- 7.2 สิทธิ์จริงของ receipt_links (ต้องมี anon=...r... และ service_role)
SELECT relname, relacl::text AS relacl
FROM pg_class
WHERE relname = 'receipt_links' AND relnamespace = 'public'::regnamespace;

-- 7.3 คอลัมน์ใหม่ใน receipts (ต้องได้ 8 แถว: ใบชั่ง 4 + สั่งซื้อ/งาน 4)
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'receipts'
  AND column_name IN ('scale_weight_in', 'scale_weight_out', 'scale_weight_net', 'vehicle_registration',
                      'company_name', 'job_name', 'requester', 'pay_approver')
ORDER BY column_name;

-- 7.4 Policy ทั้งหมดฝั่งแอนอน (3 แถว: receipts / receipt_links / doc_types)
SELECT polrelid::regclass AS tbl, polname, polcmd
FROM pg_policy
WHERE polname IN ('anon_read_receipts', 'anon_read_receipt_links', 'anon_read_active_doc_types')
ORDER BY polname;

-- 7.5 Realtime ของ receipts (1 แถว)
SELECT schemaname, tablename FROM pg_publication_tables
WHERE pubname = 'supabase_realtime' AND tablename = 'receipts';

-- ════════════════════════════════════════════════════════════
-- [8] SELF-HEAL — ให้สิทธิ์อ่านซ้ำทุกครั้งที่รัน (กันสิทธิ์หาย/โดนตีกลับ/รันครั้งแรกไม่เคย GRANT)
--     รันซ้ำกี่ครั้งก็ได้: ขั้นนี้จะ "ซ่อม" สิทธิ์ให้ครบเสมอ แล้วรายงานผล 1 แถว
-- ════════════════════════════════════════════════════════════
DO $$
BEGIN
  GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
  -- receipts: anon ต้องอ่านทั้งตารางได้ (ตัดสิทธิ์ส่วนเกินที่อาจตกค้างจากเวอร์ชันเก่า)
  REVOKE ALL ON public.receipts FROM anon, authenticated;
  GRANT SELECT ON public.receipts TO anon;
  -- receipt_links: anon/authenticated อ่านได้ (หัวใจของแท็บจับคู่ — ถ้าขาดตรงนี้หน้าเว็บจะเห็น 401)
  REVOKE ALL ON public.receipt_links FROM anon, authenticated;
  GRANT SELECT ON public.receipt_links TO anon, authenticated;
  GRANT ALL ON public.receipt_links TO service_role;
  -- AI (เอกสารสำหรับ AI): anon อ่านอย่างเดียว (ตัดสิทธิ์ส่วนเกินจากรุ่นเก่าอัตโนมัติทุกครั้งที่รัน)
  REVOKE ALL ON public.ai_templates FROM anon, authenticated;
  GRANT SELECT ON public.ai_templates TO anon;
  GRANT ALL ON public.ai_templates TO service_role;
  REVOKE ALL ON public.ai_prompts FROM anon, authenticated;
  GRANT SELECT ON public.ai_prompts TO anon;
  GRANT ALL ON public.ai_prompts TO service_role;
  -- View UI (กัน HTTP 403 — เดิมลืม GRANT → GAS/service_role อ่าน view ไม่ได้)
  REVOKE ALL ON public.v_ai_templates_ui FROM anon, authenticated;
  GRANT SELECT ON public.v_ai_templates_ui TO anon, authenticated;
  GRANT SELECT ON public.v_ai_templates_ui TO service_role;
  REVOKE ALL ON public.v_ai_prompts_ui FROM anon, authenticated;
  GRANT SELECT ON public.v_ai_prompts_ui TO anon, authenticated;
  GRANT SELECT ON public.v_ai_prompts_ui TO service_role;
  -- ai_feedback_logs (Human-in-the-Loop): GAS เขียน, anon/authenticated อ่าน history + Realtime
  REVOKE ALL ON public.ai_feedback_logs FROM anon, authenticated;
  GRANT SELECT ON public.ai_feedback_logs TO anon, authenticated;
  GRANT ALL ON public.ai_feedback_logs TO service_role;
  REVOKE ALL ON public.vendor_billing_notes FROM anon, authenticated;
  GRANT SELECT ON public.vendor_billing_notes TO anon, authenticated;
  GRANT ALL ON public.vendor_billing_notes TO service_role;
  REVOKE ALL ON public.vendor_billing_items FROM anon, authenticated;
  GRANT SELECT ON public.vendor_billing_items TO anon, authenticated;
  GRANT ALL ON public.vendor_billing_items TO service_role;
  -- doc_types: anon/authenticated อ่านเฉพาะแถว is_active=true (RLS คุม) — เขียน/ลบผ่าน GAS (service_role) เท่านั้น
  REVOKE ALL ON public.doc_types FROM anon, authenticated;
  GRANT SELECT ON public.doc_types TO anon, authenticated;
  GRANT ALL ON public.doc_types TO service_role;
  -- receipt_learning: ปิด anon/authenticated สนิท (ใช้ GAS/service_role เท่านั้น) — self-heal คงสถานะปิดเสมอ
  REVOKE ALL ON public.receipt_learning FROM anon, authenticated;
  GRANT ALL ON public.receipt_learning TO service_role;
  -- Views ธุรกิจ (section 7.1E): อ่านได้ทุกบทบาท — กัน 403 เมื่อสิทธิ์หาย
  GRANT SELECT ON public.bills, public.purchase_orders, public.po_invoice_matches, public.ai_document_templates
    TO anon, authenticated, service_role;
  RAISE NOTICE 'SELF-HEAL: ตรวจ/ซ่อมสิทธิ์ครบ (receipts/receipt_links/doc_types/receipt_learning/ai_templates/ai_prompts/views AI+ธุรกิจ/ai_feedback_logs/vendor_billing_* = anon อ่านตามสเปก, service_role เต็ม) — ปิด 401/403 + กันสิทธิ์เกินแล้ว';
END $$;

-- รายงานผล 1 แถว (มี 3 คอลัมน์ — ถ้า numbers ครบ = ผ่านหมด ให้วางผลแถวนี้มาถ้าอยากให้ผมเช็ค)
SELECT
  (SELECT count(*) FROM pg_class WHERE relname = 'receipt_links' AND relnamespace = 'public'::regnamespace) AS has_table,
  (SELECT COALESCE(string_agg(a::text, '; '), '-')
     FROM unnest((SELECT relacl FROM pg_class
                  WHERE relname = 'receipt_links' AND relnamespace = 'public'::regnamespace)) a) AS grants,
  (SELECT count(*) FROM pg_policy WHERE polrelid = 'public.receipt_links'::regclass) AS policies;

-- ════════════════════════════════════════════════════════════
-- [14] RUNNING NUMBER TR-YYYYMM-##### (Atomic Sequential Lock ฝั่ง DB) + MD5 Hashed Image Key
--   - receipts.running_number  = เลข TR ที่คนเห็น/พูดถึงจริง (ใบหน้าในแชท/ชื่อไฟล์ Drive/เว็บ) — unique ไม่ซ้ำ
--   - receipts.system_record_no = เลขอ้างอิงเชิงเทคนิค (ตัวตนบิล) ตามเดิม
--   - receipts.image_md5        = แฮชไฟล์รูป MD5 (กันส่งรูปเดิมซ้ำก่อนเข้าสู่ Gemini OCR)
--   รันซ้ำได้ (idempotent): คอลัมน์/ตาราง/ฟังก์ชัน = IF NOT EXISTS, backfill เฉพาะแถวที่ยังว่าง
-- ════════════════════════════════════════════════════════════
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS running_number text;
ALTER TABLE public.receipts ADD COLUMN IF NOT EXISTS image_md5 text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_receipts_running_number ON public.receipts (running_number) WHERE running_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_receipts_image_md5 ON public.receipts (image_md5) WHERE image_md5 IS NOT NULL;

-- atomic sequential counter (แถวเดียว + FOR UPDATE = จองเลขแบบมือเดียว ไม่ซ้ำดุเดือด)
CREATE TABLE IF NOT EXISTS public.running_number_counter (
  id smallint PRIMARY KEY CHECK (id = 1),
  last_month text NOT NULL DEFAULT '',
  last_no bigint NOT NULL DEFAULT 0
);

-- RPC จองเลข TR เดือนถัดไป: row lock → เลขถัดไป ไม่ต้องรอ JavaScript math ฝั่ง GAS
CREATE OR REPLACE FUNCTION public.next_running_number(p_month text)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_last text;
  v_no bigint;
BEGIN
  INSERT INTO public.running_number_counter (id, last_month, last_no) VALUES (1, '', 0)
  ON CONFLICT (id) DO NOTHING;
  SELECT last_month, last_no INTO v_last, v_no FROM public.running_number_counter WHERE id = 1 FOR UPDATE;
  IF COALESCE(v_last, '') = p_month THEN
    v_no := v_no + 1;
  ELSE
    v_last := p_month;
    v_no := 1;
  END IF;
  UPDATE public.running_number_counter SET last_month = v_last, last_no = v_no WHERE id = 1;
  RETURN 'TR-' || p_month || '-' || lpad(v_no::text, 5, '0');
END;
$$;

-- RPC ซิงก์ counter ให้สอดคล้องกับเลข TR ที่ backfill ไปแล้วของเดือนปัจจุบัน (กันชนกับเลขเก่า)
CREATE OR REPLACE FUNCTION public.sync_running_number_counter()
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_month text := to_char(now() AT TIME ZONE 'Asia/Bangkok', 'YYYYMM');
  v_max bigint;
BEGIN
  INSERT INTO public.running_number_counter (id, last_month, last_no) VALUES (1, '', 0)
  ON CONFLICT (id) DO NOTHING;
  SELECT COALESCE(max((regexp_split_to_array(running_number, '-'))[3]::bigint), 0) INTO v_max
  FROM public.receipts
  WHERE running_number IS NOT NULL AND running_number LIKE 'TR-' || v_month || '-%';
  UPDATE public.running_number_counter
     SET last_month = v_month, last_no = GREATEST(COALESCE(last_no, 0), v_max)
   WHERE id = 1;
END;
$$;

-- มือที่จองเลขได้ = เฉพาะ GAS/webhook (service_role) — หน้าเว็บ/anon จองเองไม่ได้
REVOKE ALL ON FUNCTION public.next_running_number(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.next_running_number(text) TO service_role;
REVOKE ALL ON FUNCTION public.sync_running_number_counter() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.sync_running_number_counter() TO service_role;

-- backfill: ใส่ TR ให้แถวเก่าที่ยังว่าง (เรียง created_at เดือนละเดือน → ได้ตัวเลขเดิมทุกครั้งที่รันซ้ำ)
-- หมายเหตุ: ใช้ COALESCE(created_at, submitted_at) — เพราะบิลเก่าบางชุด submitted_at เป็น NULL (บันทึกไม่ลงค่า)
--          created_at = ตอนที่ระบบรับบิลเข้า DB (default now()) มีค่าเสมอ
WITH numbered AS (
  SELECT ctid,
         'TR-' || to_char(COALESCE(created_at, submitted_at) AT TIME ZONE 'Asia/Bangkok', 'YYYYMM') || '-' ||
         lpad((row_number() OVER (PARTITION BY to_char(COALESCE(created_at, submitted_at) AT TIME ZONE 'Asia/Bangkok', 'YYYYMM')
                                   ORDER BY COALESCE(created_at, submitted_at) ASC, ctid))::text, 5, '0') AS rn
  FROM public.receipts
  WHERE running_number IS NULL
)
UPDATE public.receipts r SET running_number = n.rn
FROM numbered n WHERE r.ctid = n.ctid;

SELECT public.sync_running_number_counter();

-- รายงานผล TR 5 ใบล่าสุด + counter (ถ้าได้ตัวเลข TR-YYYYMM-xxxxx = พร้อมใช้)
SELECT running_number, system_record_no, doc_key
FROM public.receipts
WHERE running_number IS NOT NULL
ORDER BY created_at DESC
LIMIT 5;

SELECT last_month, last_no FROM public.running_number_counter;

-- ════════════════════════════════════════════════════════════
-- [15] WEIGHT & UNIT VARIANCE ENGINE (โซ่ PO → ใบส่งของ → ใบชั่ง)
--     เทียบจำนวน/น้ำหนักที่ส่งจริงกับ PO เก็บระดับความรุนแรงให้หน้าเว็บโชว์ยางธง
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.weight_variances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_doc_key text NOT NULL,
  bill_doc_key text NOT NULL,
  scale_doc_key text,
  po_no text DEFAULT '',
  store_name text DEFAULT '',
  expected_qty numeric,
  delivered_qty numeric,
  qty_variance_pct numeric,
  expected_weight_kg numeric,
  scale_weight_kg numeric,
  weight_variance_pct numeric,
  severity text DEFAULT 'ok' CHECK (severity IN ('ok','low','high')),
  review_status text DEFAULT 'open' CHECK (review_status IN ('open','reviewed')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (po_doc_key, bill_doc_key)
);

ALTER TABLE public.weight_variances ENABLE ROW LEVEL SECURITY;

-- สิทธิ์: anon/authenticated อ่านได้ (โชว์หน้างาน), เขียนผ่าน GAS (service_role) เท่านั้น
REVOKE ALL ON public.weight_variances FROM anon, authenticated;
GRANT SELECT ON public.weight_variances TO anon, authenticated;
GRANT ALL ON public.weight_variances TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policy
                 WHERE polrelid = 'public.weight_variances'::regclass
                   AND polname = 'anon_read_weight_variances') THEN
    CREATE POLICY anon_read_weight_variances ON public.weight_variances
      FOR SELECT TO anon USING (true);
  END IF;
END $$;

-- รายงานความต่างที่พบ 5 รายการล่าสุด (ถ้ายังว่าง = ยังรอ GAS รัน runWeightVarianceCheck)
SELECT po_doc_key, bill_doc_key, po_no, expected_qty, delivered_qty, qty_variance_pct,
       scale_weight_kg, severity
FROM public.weight_variances
ORDER BY created_at DESC
LIMIT 5;
